version: '3'
services:
  gateway_service:
    build: .
    networks:
      - "service_net"
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    networks:
      - service_net
networks:
  service_net: