apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: <python-app-image>
        env:
        - name: MICROSERVICE_URL
          value: http://transaction-service:8080/api
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USERNAME
          value: alice
        - name: REDIS_PASSWORD
          value: alicepassword